server:
  port: 8090

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-clubs
          uri: lb://ms-clubs
          predicates:
            - Path=/club/**

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
#    hostname: localhost
    hostname: ec2-54-234-215-181.compute-1.amazonaws.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway