name: Build & Deploy Eureka & Api Gateway

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-discovery/**'
      - 'backend/ms-gateway/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-discovery/**'
      - 'backend/ms-gateway/**'

jobs:
  config-aws:
    name: Config AWS credentials
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  build-eureka:
    name: Build Eureka with Maven
    runs-on: ubuntu-latest      
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Eureka
      run: |
        echo "Building app..."
        cd backend/ms-discovery
        mvn clean install
        echo "Finished building the app."

    - name: Archive Backend Build
      uses: actions/upload-artifact@v2
      with:
        name: eureka
        path: backend/ms-discovery/target/ms_discovery.jar

  deploy-eureka:
    needs: build-eureka
    name: Deploy Eureka Server
    runs-on: ubuntu-latest
    steps:

    - name: Download Eureka Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: eureka

    - name: Deploy Eureka
      run: |
          echo "Deploying started..."
          ssh ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY "sudo systemctl stop eureka.service"
          scp backend/ms-discovery/target/ms_discovery.jar ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY:~/app/eureka
          ssh ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY "sudo systemctl start eureka.service"
          echo "Finished deploying the app."

  build-gateway:
    name: Build Gateway with Maven
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Gateway
      run: |
        echo "Building app..."
        cd backend/ms-gateway
        mvn clean install
        echo "Finished building the app."

    - name: Archive Backend Build
      uses: actions/upload-artifact@v2
      with:
        name: gateway
        path: backend/ms-gateway/target/ms_gateway.jar

  deploy-gateway:
    needs: build-gateway
    name: Deploy Gateway Server
    runs-on: ubuntu-latest
    steps:

    - name: Download Gateway Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: gateway

    - name: Build Api Gateway
      run: |
        echo "Deploying started..."
        ssh ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY "sudo systemctl stop gateway.service"
        scp backend/ms-gateway/target/ms_gateway.jar ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY:~/app/gateway
        ssh ubuntu@$DEPLOY_SERVER_IP_EUREKA_GATEWAY "sudo systemctl start gateway.service"
        echo "Finished deploying the app."