name: Build Api Gateway 

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-gateway/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-gateway/**'

jobs:
 build-gateway:
    runs-on: [self-hosted, linux, X64, gateway]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Maven package Api Gateway
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-gateway
        mvn -B package --file pom.xml

    - name: Build Api Gateway
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-gateway
        sudo systemctl stop gateway.service
        cp target/ms_gateway.jar /home/ubuntu/app/gateway
        sudo systemctl start gateway.service
