name: Build MS Bookings

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-bookings/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-bookings/**'

jobs:
 build-booking:
    runs-on: [self-hosted, linux, X64, api-3]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Set Environment Variables
      run: |
        echo "export BD_URL=${{ secrets.BD_URL }}" >> $GITHUB_ENV
        echo "export BD_USERNAME=${{ secrets.BD_USERNAME }}" >> $GITHUB_ENV
        echo "export BD_PASSWORD=${{ secrets.BD_PASSWORD }}" >> $GITHUB_ENV
        echo "export SENDER_EMAIL_USERNAME=${{ secrets.SENDER_EMAIL_USERNAME }}" >> $GITHUB_ENV
        echo "export SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}" >> $GITHUB_ENV

    - name: Maven package Booking
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-bookings
        mvn -B package --file pom.xml
        
    - name: Build Booking
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-bookings
        sudo systemctl stop booking.service
        cp target/ms_bookings.jar /home/ubuntu/booking
        sudo systemctl start booking.service
