name: Build MS Clubs

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-clubs/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-clubs/**'

jobs:
 build-clubs:
    runs-on: [self-hosted, linux, X64, clubs]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Maven package Clubs
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-clubs
        mvn -B package --file pom.xml
        
    - name: Build Clubs
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-clubs
        sudo systemctl stop eureka.service
        cp target/ms_discovery.jar /home/ubuntu/app/eureka
        sudo systemctl start eureka.service
