name: Build MS Clubs

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-clubs/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-clubs/**'

jobs:
 build-club:
    runs-on: [self-hosted, linux, X64, api-1]
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '3'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        # cache: 'maven'

    - name: Maven package Club
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-clubs
        mvn clean
        mvn -B package --file pom.xml
        
    - name: Build Club
      run: |
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-clubs
        sudo systemctl stop club.service
        cp target/ms_clubs.jar /home/ubuntu/club
        sudo systemctl start club.service
