name: Build MS Users

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-users/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-users/**'

jobs:
 build-user:
    runs-on: [self-hosted, linux, X64, api-2]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Set Environment Variables
      run: |
        echo "export BD_URL=${{ secrets.BD_URL }}" >> $GITHUB_ENV
        echo "export BD_USERNAME=${{ secrets.BD_USERNAME }}" >> $GITHUB_ENV
        echo "export BD_PASSWORD=${{ secrets.BD_PASSWORD }}" >> $GITHUB_ENV
        echo "export SENDER_EMAIL_USERNAME=${{ secrets.SENDER_EMAIL_USERNAME }}" >> $GITHUB_ENV
        echo "export SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}" >> $GITHUB_ENV

    - name: Maven package User
      run: |
        env
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-users
        mvn -B package --file pom.xml
        
    - name: Build User
      run: |
        env
        cd /home/ubuntu/actions-runner/_work/Grupo-5/Grupo-5/backend/ms-users
        sudo systemctl stop user.service
        cp target/ms_users.jar /home/ubuntu/user
        sudo systemctl start user.service
