server:
  port: ${PORT:8761}

spring:
  application:
    name: Eureka-server
eureka:
  instance:
#    hostname: localhost
    hostname: ec2-50-17-115-59.compute-1.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG